{
  #データ作成関係
  "data_path" : "input_data.csv", #入力データのパス
  "huge_data" : True, #入力データが大きいかどうか(目安として10万行以上かどうか)
  "sentence_index" : 1, #入力データで文章が書いてある列番号
  "label_index" : 0, #入力データでラベルが書いてある列番号
  "label_to_zen" : False, #ラベルを全角にするかどうか. 半角と全角が混在するときはTrueにする. label_dictの方でラベルを全角にすることを忘れないように
  "label_dict" : , #ラベルを別の文字列に置き換えたい時に使用. mapで指定すること. 使用しない場合は何も書かない
  "TARGET_CATEGORIES": ["名詞"], #使用する品詞
  "EXCLUDE_CATEGORIES": ["代名詞","数","非自立"], #使用する品詞の中で除外したい品詞
  "words_num" : 10000, #出現頻度上位何単語を使用するか

  #高度なオプション(データ作成関係)
  
  
  #データ出力関係
  "wordlist_path" : "word_list.txt", #出力する単語リストのパス
  "output_path" : "test.dat", #自己組織化マップ用の入力ベクトルファイルのパス
}